name: TestCI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: ./gradlew test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-reports
          path: |
            allure-results

  
